In [4]:
import numpy as np

# 1. Creating NumPy arrays

# 1.1. Initializing an array with zeros
# Create a 3x3 array filled with zeros
zeros_array = np.zeros((3, 3))
print(zeros_array)

# 1.2. Initializing an array with ones
# Create a 2x4 array filled with ones
ones_array = np.ones((2, 4))
print(ones_array)

# 1.3. Initializing an array with random numbers:
# Create a 3x3 array with random values
random_array = np.random.rand(3, 3)
print(random_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0.43994954 0.86564596 0.44088389]
 [0.61499822 0.52709112 0.36660148]
 [0.3259429  0.38950855 0.82220996]]


In [5]:
# 2. Basic operations on NumPy arrays

# 2.1. Array addition:
array_1 = np.array([[1, 2], [3, 4]])
array_2 = np.array([[5, 6], [7, 8]])
sum = array_1 + array_2
print(sum)

# 2.2. Array multiplication:
product = array_1 * array_2
print(product)

[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]


In [6]:
# 3. Indexing, slicing, and reshaping NumPy arrays

# 3.1. Indexing
element = array_1[1, 1]
print(element)

# 3.2. Slicing
# Extract the first row
first_row = array_1[0, :]
print(first_row)

# Extract the second column
second_column = array_1[:, 1]
print(second_column)

# 3.3. Reshaping
array = np.array([1, 2, 3, 4, 5, 6])
reshaped_array = array.reshape((2, 3))
print(reshaped_array)

4
[1 2]
[2 4]
[[1 2 3]
 [4 5 6]]


In [9]:
# 4. Matrix operations in NumPy

# 4.1. Creating and manipulating matrices
matrix_1 = np.array([[1, 2], [3, 4]])
element = matrix_1[0, 1]
print(element)

# 4.2. Matrix addition, subtraction, multiplication, and division
matrix_2 = np.array([[5, 6], [7, 8]])
matrix_sum = matrix_1 + matrix_2
matrix_product = matrix_1 * matrix_2

print(matrix_sum)
print(matrix_product)

# 4.3. Matrix transposition and inverse
# Matrix transposition: swap its rows and columns
transposed_matrix = matrix_1.transpose() # = matrix_1.T
print(transposed_matrix)
# Inverse of a matrix:
inverse_matrix = np.linalg.inv(matrix_1)
print(inverse_matrix)

# 4.4. Matric multiplication and dot product
# Matrix multiplication is different from element-wise multiplication.
matrix_multiplication = np.dot(matrix_1, matrix_2)
print(matrix_multiplication)

2
[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]
[[1 3]
 [2 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[19 22]
 [43 50]]
