# NumPy for Linear Algebra

Python, especially with the help of the NumPy library, allows easy manipulation of vectors and matrices. In addition to basic operations, NumPy supports advanced linear algebra operations such as dot products, cross products, matrix decompositions, and the caluculation of eigenvalues and eigenvectors.

## Vector manipulation

### Vector basic operations

In [9]:
import numpy as np

# Define vectors
vector_a = np.array([1, 2, 3])
vector_b = np.array([4, 5, 6])

# Vector addition
result_add = vector_a + vector_b
print(result_add)

# Vector subtraction
result_sub = vector_a - vector_b
print(result_sub)

# Scalar mutiplication
result_scalar_mul = 2 * vector_a
print(result_scalar_mul)

[5 7 9]
[-3 -3 -3]
[2 4 6]


### Dot product and Cross product

The dot product returns a scalar, while the cross product returns a vector perpendicular to the plne defined by the original vectors.

In [14]:
import numpy as np

# Define vectors
vector_a = np.array([1, 2, 3])
vector_b = np.array([4, 5, 6])

# Dot product
dot_product = np.dot(vector_a, vector_b) 
#dot_product = vector_a @ vector_b
print(dot_product)

# Cross product
cross_product = np.cross(vector_a, vector_b)
print(cross_product)

32
[-3  6 -3]


## Matix manipulation

### Matrix basic operations

In [18]:
import numpy as np

# Define matrices
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])

# Matrix addition
result_add = matrix_a + matrix_b
print(result_add)

# Matrix subtraction
result_sub = matrix_a - matrix_b
print(result_sub)

# Matrix multiplication (elemen-wise)
result_mul = matrix_a * matrix_b
print(result_mul)

# Matrix multiplication (dot product)
result_dot = np.dot(matrix_a, matrix_b) 
#result_dot = matrix_a @ matrix_b
print(result_dot)

# Matrix rank
print(np.linalg.matrix_rank(matrix_a))

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]
2


### Matrix inversion and Determinants

Matrix inversion and determinant calculations are commonly used in linear algebra. The NumPy library provides function to perform these operations through `numpy.linalg`.

In [7]:
import numpy as np

# Define matrix
matrix = np.array([[1, 2], [3, 4]])

# Matrix inversion
matrix_inv = np.linalg.inv(matrix)
print(matrix_inv)

# Matirx determinant
matrix_det = np.linalg.det(matrix)
print(matrix_det)

[[-2.   1. ]
 [ 1.5 -0.5]]
-2.0000000000000004


### Eigenvalues and Eigenvectors

Eigenvalues and eigenvectors are fundamental concepts in linear algebra, particularly useful in systems of equations, stability analysis, and more.

In [19]:
import numpy as np

# Define matrix
matrix = np.array([[1, 2], [3, 2]])
eigenvalues, eigenvectors = np.linalg.eig(matrix)

print(f"Eigenvalues: {eigenvalues}")
print(f"Eigenvectors:\n {eigenvectors}")

Eigenvalues: [-1.  4.]
Eigenvectors:
 [[-0.70710678 -0.5547002 ]
 [ 0.70710678 -0.83205029]]


## Solving systems of linear equations

Solving systems of linear equations is a fundamental problem in mathematical and science. In Python, there are several methods available to solve these problems efficiently, particularly when the system of equations can be represented as a matrix equation.

One of the most common methods to solve a system of linear equations is by using the matrix inverse. Given a system of equations: $A\text{x}=\text{b}$, where $A$ is a matrix, $\text{x}$ is the vector of unknowns, and $\text{b}$ is the vector of constants, we can solve for $\text{x}$ by computing the inverse of matrix $A$: $\text{x}=A^{-1}\text{b}$. This method workds well when the matrix $A$ is invertible.

In [21]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
b = np.array([5, 6])

A_inv = np.linalg.inv(A);

x = A_inv @ b
print(x)

[-4.   4.5]
