# NumPy Introduction

## Basic information about NumPy

### What is NumPy?

NumPy is a Python library used for working with arrays. It also has functions for working in domain of linear algebra, fourier transform, and matrices.

NumPy wa created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

NumPy stands for Numerical Python.

### Why use NumPy?

In Python, we have lists that serve the purpose of arrays, but they are slow to process. NumPy aims to provide an array object that is up to 50x faster than traditional Python lists. The array object in NumPy is called `ndarray`, it provides a lot of supporintg functions that make working with `ndarray` very easy.

Arrays are very frequently used in data science, where speed and resources are very important.

### Why is NumPy faster than Lists?

NumPy arrays are stored at one continous place in memory unlike lists, so processes can access and manipulate them very efficiently. This behavior is called locality of reference in computer science. This is the main reason why NumPy is faster than Lists. Also it is optimized to work with latest CPU architectures.

### Which language is NumPy written in?

NumPy is a Python library and is written partially in Python, but mose of the parts that require fast computation are written in `C` or `C++`.

The source code for NumPy is located at this GitHub repository: [NumPy](https://github.com/numpy/numpy).

## NumPy creating arrays

NumPy is used to work with arrays, the array object in NumPy is called `ndarray`.

In [ ]:
import numpy as np

arr0 = np.array(42) # 0-dimension array
arr1 = np.array([1, 2, 3, 4, 5]) # 1-dimension array
arr2 = np.array([[1, 2, 3], [4, 5, 6]]) # 2-dimension array

print(type(arr0))
print(arr0)
print(arr1)
print(arr2)

# Check how many dimensions the arrays have:
print(arr0.ndim)
print(arr1.ndim)
print(arr2.ndim)

# Higher dimensional arrays:
arr5 = np.array([1, 2, 3, 4, 5], ndmin = 5)
print(arr5)
print(f"Dimensions: {arr5.ndim}")

# Create repeated arrays:
arr = np.full((2, 3), 7) # Matrix 2x3 with filled by full 7
print(arr)

arr = np.tile([1, 2, 3], (2, 3)) # [1, 2, 3] is repeated 2x3 times
print(arr)

# Create empty arrays:
arr = np.empty((2, 3))
print(arr)

# Create diagonal matrices:
arr = np.diag([1, 2, 3]) # Create from a list
print(arr)

arr = np.diag([1]*4) # Create with diagonal has the same value
print(arr)

# Create lists filled with evenly spaced numerical values within a specified range:
arr = np.arange(1, 10, 2) # Protocol: [start:stop:step]
print(arr)

# Print unique values (ascending order) of arrays:
arr = np.array([1, 2, 2, 5, 4, 5, 1, 6])
print(np.unique(arr))

<class 'numpy.ndarray'>
42
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
0
1
2
[[[[[1 2 3 4 5]]]]]
Dimensions: 5
[[7 7 7]
 [7 7 7]]
[[1 2 3 1 2 3 1 2 3]
 [1 2 3 1 2 3 1 2 3]]
[[3.5e-323 3.5e-323 3.5e-323]
 [3.5e-323 3.5e-323 3.5e-323]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
[1 3 5 7 9]
[1 2 4 5 6]


## Indexing and Slicing in NumPy arrays

### Indexing

The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1, etc.

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr[0][1]) # Method 1
print(arr[0, 2]) # Method 2

# Negative indexing:
print(arr[-1, -1]) # print the bottom right element

2
3
8


### Slicing

Slicing in Python means taking elements form one given index to another given index. We pass slice instead of index like this: `[start:end]`. We can also define the step like this: `[start:end:step]`.

- If we do not pass `start`, its considered 0.
- If we do not pass `end`, its considered length of array in that dimension.
- If we do not pass `step`, its considered 1.

In [20]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr[0, :]) # Print first row

# Negative slicing:
# Two method but have the same result:
print(arr[0, 1:3])
print(arr[0, -3:-1])

# Reversed slicing
print(arr[0, -1:-3:-1])

[1 2 3 4]
[2 3]
[2 3]
[4 3]


## Data types in NumPy arrays

We use the `array()` function to create arrays, this function can take an optional argument: `dtype` that allows use to define the expected data type of the array elements.

Below is a list of all data types in NumPy and the characters used to represent them:

- `i` - integer
- `b` - boolean
- `u` - unsigned integer
- `f` - float
- `c` - complex float
- `m` - timedelta
- `M` - datetime
- `O` - object
- `S` - string
- `U` - unicode string
- `V` - fixed chunk of memory for other type (void)

In [ ]:
import numpy as np

# Checking data type of array object:
arr = np.array([1, 2, 3, 4])
print(arr.dtype)

# Create array with expected data type:
arr = np.array([1, 2, 3, 4], dtype = 'f')
print(arr)
print(arr.dtype)

int64
[1. 2. 3. 4.]
float32


If a type is given in which elements cannot be casted then NumPy will raise a ValueError.

In [6]:
import numpy as np

# Converting data type on existing arrays:
arr = np.array([1.1, 2.1, 3.1])

new_arr = arr.astype('i') # new_arr = arr.astype(int)
print(new_arr)
print(new_arr.dtype)

[1 2 3]
int32


## View and Copy

The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

The copy _owns_ the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

In contrast, the view _does not own_ the data and any changes made to the view or the original array, will affect the another.

In [ ]:
import numpy as np

# Copy
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()

x[0] = 6
print(arr) # arr is modifed
print(x) 

# View
arr = np.array([1, 2, 3, 4, 5])
y = arr.view()

y[0] = 6
print(arr) # arr is not modified
print(y)

## Check is array owns its data
print(x.base)
print(y.base)

[1 2 3 4 5]
[6 2 3 4 5]
[6 2 3 4 5]
[6 2 3 4 5]
None
[6 2 3 4 5]


`base` attribute refers to the original object, so:

- The copy returns `None`.
- The view returns the original array.

## Array shape and reshape

The shape of an array is the number of elements in each dimension.

In [18]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)

arr = np.array([1, 2, 3, 4], ndmin = 3) # 3 dimensions
print(arr.shape)

(2, 4)
(1, 1, 4)


In [23]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

new_arr = arr.reshape(2, 4)
print(new_arr)

# other_new_arr = arr.reshape(2, 3) # Error

print(new_arr.base)

[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]


The last result means that reshaped array is a view. Then, if we modify the reshaped array, the original one is also changed. To avoid this, make a copy first, and reshape the copy.

### Unknown dimension

Pass `-1` as the value, and NumPy will calculate this number for you.

_Note: you can change `-1` by any negative integer, but `-1` is a convention._

In [24]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
new_arr = arr.reshape(2, 2, -1)
print(new_arr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Flattening the arrays

Flattening array means converting a multidimensional array into a 1D array.

In [35]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

new_arr = arr.reshape(6) # Shouldn't use
new_arr = arr.reshape(-1)
print(new_arr)

[1 2 3 4 5 6]


## Array iterating

In [40]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
for x in arr[:, ::2]:
    print(x)

# Iterating with index
for pos, x in np.ndenumerate(arr):
    print(f"{pos}: {x}")

[1 3]
[4 6]
[7 9]
(0, 0): 1
(0, 1): 2
(0, 2): 3
(1, 0): 4
(1, 1): 5
(1, 2): 6
(2, 0): 7
(2, 1): 8
(2, 2): 9


## NumPy Joining arrays

Joining means putting contens of two or more arrays in a single array. 

In SQL we join tables based  on key, whereas in NumPy we join arraays by axes. We pass a sequence off arrays that we want to join to the `concatenate()` function, along with the axis. If the axis is not explicitly passed, it is taken as 0.

NumPy arrays have shape like `(a, b, c, ...)`, then parameter `axis` is based on `0, 1, 2, ...` respectively.

In [ ]:
import numpy as np

arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[4, 5, 6], [7, 8, 9]])

arr = np.concatenate((arr1, arr2), axis = 1)
# arr = np.concatenate((arr1, arr2), axis = 0) # Error

print(arr)

[[1 2 3 4 5 6]
 [4 5 6 7 8 9]]


Before merging, you can reshape the array to avoid dimensioning errors.

In [13]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1.reshape(1,-1), arr2.reshape(1,-1)), axis = 0)

print(arr)

[[1 2 3]
 [4 5 6]]


## NumPy Splitting array

Splitting is reverse operation of Joining. Joing merges multiple arrays into one and Splitting breaks one array into multiple.

We use `array_split()` for splitting arrays, we pass it the array we want to split and the number of splits.

The `axis` parameter has the same meaning as in `concatenate()`.

In [17]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis = 0)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


## Searching arrays in NumPy

You can search an array for  a certain value, adn return the indexes that get a match. To search an array, use the `where()` method.

In [20]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4) # Find indexes of value 4
print(x)

x = np.where(arr%2 == 1) # Find indexes of odd value
print(x)

(array([3, 5, 6]),)
(array([0, 2, 4]),)


## Sorting Arrays in NumPy

Sorting means putting elements in an ordered sequence. Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.

In [3]:
import numpy as np

# Sorting for 1-D array
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))

# Sorting for 2-D array
arr = np.array([[1, 4, 2], [5, 7, 3]]) # Sort on each element
print(np.sort(arr))

# Index after sorted
arr = np.array([5, 3, 4, 1])
index_sort = np.argsort(arr)
print(index_sort)

# Sorting in descending order

arr = np.array([5, 3, 4, 1, 2])
print(np.sort(arr)[::-1]) # print(np.sort(-arr))
print(np.argsort(arr)[::-1]) # print(np.argsort(-arr))

[0 1 2 3]
[[1 2 4]
 [3 5 7]]
[3 1 2 0]
[5 4 3 2 1]
[0 2 1 4 3]
