Python provides a wide range of basic arithmetic operations that can be used to perform calculations in a straigthtforward and intuitive manner. These operations include addition, subtraction, multiplication, and division.

In [2]:
# 1. Addition, subtraction, multiplication, and division

result_add = 5 + 3
print(f"Addition: 5 + 3 = {result_add}")

result_sub = 10 - 4
print(f"Subtraction: 10 - 4 = {result_sub}")

result_mul = 7 * 6
print(f"Multiplication: 7 * 6 = {result_mul}")

result_div = 20 / 4
print(f"Division: 20 / 4 = {result_div}")

Addition: 5 + 3 = 8
Subtraction: 10 - 4 = 6
Multiplication: 7 * 6 = 42
Division: 20 / 4 = 5.0


In [3]:
# 2. Exponential and logarithm functions

import math

result_exp = 2 ** 3
print(f"Exponentiation: 2^3 = {result_exp}")

result_log = math.log(10) # Base e (natural logarit)
print(f"Logarithm (base e): log(10) = {result_log}")

result_log10 = math.log10(100)
print(f"Logarithm (base 10): log10(100) = {result_log10}")

Exponentiation: 2^3 = 8
Logarithm (base e): log(10) = 2.302585092994046
Logarithm (base 10): log10(100) = 2.0


In [4]:
# 3. Absolute value, maximum, and minimum calculations

result_abs = abs(-7)
print(f"Absolute value of -7: {result_abs}")

result_max = max(3, 5, 2, 8)
print(f"Maximum value: {result_max}")

result_min = min(3, 5, 2, 8)
print(f"Minimum value: {result_min}")

Absolute value of -7: 7
Maximum value: 8
Minimum value: 2


In [5]:
# 4. Vector addition, subtraction, amd scalar multiplication

import numpy as np

vector_a = np.array([1, 2, 3])
vector_b = np.array([4, 5, 6])

result_add = vector_a + vector_b
print(f"Vector addition: {result_add}")

result_sub = vector_a - vector_b
print(f"Vector subtraction: {result_sub}")

result_scalar_mul = 2 * vector_a
print(f"Scalar multiplication: {result_scalar_mul}")

Vector addition: [5 7 9]
Vector subtraction: [-3 -3 -3]
Scalar multiplication: [2 4 6]


In [ ]:
# 5. Matric addition, subtraction, and multiplication

matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])

result_add = matrix_a + matrix_b
print(f"Matrix addition:\n {result_add}")

result_sub = matrix_a - matrix_b
print(f"Matrix subtraction:\n {result_sub}")

result_mul = matrix_a * matrix_b
print(f"Matrix multiplication:\n {result_mul}")

result_dot = np.dot(matrix_a, matrix_b)
print(f"Matrix multiplication (dot product):\n {result_dot}")

Matrix addition:
 [[ 6  8]
 [10 12]]
Matrix subtraction:
 [[-4 -4]
 [-4 -4]]
Matrix multiplication:
 [[ 5 12]
 [21 32]]


AttributeError: module 'numpy.linalg' has no attribute 'dot'

In [ ]:
# 6. Matrix inversion and determinants

matrix_c = np.array([[1, 2], [3, 4]])
matrix_inv = np.linalg.inv(matrix_c)
print(f"Matrix inversion:\n {matrix_inv}")

matrix_det = np.linalg.det(matrix_c)
print(f"Determinant of the matrix: {matrix_det}")

Matrix inversion:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Determinant of the matrix: -2.0000000000000004
