In addition to basic operations, NumPy supports advanced linear algebra operations such as for products, corss products, matrix, decompositions, and the calculation of eigenvalues and eigenvectors.

In [2]:
# 1. Dot product and cross product of vectors

import numpy as np

vector_a = np.array([1, 2, 3])
vector_b = np.array([4, 5, 6])

dot_product = np.dot(vector_a, vector_b)
print(f"Dot product: {dot_product}")

cross_product = np.cross(vector_a, vector_b)
print(f"Cross product: {cross_product}")

Dot product: 32
Cross product: [-3  6 -3]


In [ ]:
# 2. Matrix decompositions: LU, QR decomposition

# QR decomposition
matrix_d = np.array([[12, -51, 4], [6, 167, -68], [-4, 24, -41]])
q, r = np.linalg.qr(matrix_d)
print(f"Q matrix:\n {q}") # Q @ Q.T = In
print(f"R matrix:\n {r}") # R is an upper triangular matrix

# LU decomposition can be performed using scipy library
import scipy.linalg as la
p, l, u = la.linalg(matrix_d)
print(f"L matrix:\n {l}")
print(f"U matrix:\n {u}")

Q matrix:
 [[-0.85714286  0.39428571  0.33142857]
 [-0.42857143 -0.90285714 -0.03428571]
 [ 0.28571429 -0.17142857  0.94285714]]
R matrix:
 [[ -14.  -21.   14.]
 [   0. -175.   70.]
 [   0.    0.  -35.]]


In [4]:
# 3. Eigenvalues and eigenvectors
# Eigenvalues and eigenvectors are fundamental concepts in linear algebra, particular useful in systems of equations, stability analysis, and more.

matrix_e = np.array([[1, 2], [3, 4]])
eigenvalues, eigenvectors = np.linalg.eig(matrix_e)

print(f"Eigenvalues: {eigenvalues}")
print(f"Eigenvectors: {eigenvectors}")

Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors: [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
